services:
  influxdb:
    image: influxdb:2
    container_name: pokeprice-influx
    ports:
      - '8086:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb2
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: pokeprice-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  influxdb-data:
  postgres-data:
